#define EXPRESS 0
#define LOCAL 1
#define FREIGHT 2
#define MAINTENANCE 3

#define RED 0
#define GREEN 1
#define FLASHING_YELLOW 2

mtype = {ARRIVAL_REQUEST, TRACK_AVAILABLE, TRACK_UNAVAILABLE, MAINTENANCE_REQUEST};
